version: '2'
services:
  phabricator:
    restart: always
    ports:
     - "8080:80"
    volumes:
     - ./data/config.json:/opt/phabricator/conf/local/local.json
    depends_on:
     - mysql
    links:
     - mysql
    image: phabricator
  mysql:
    restart: always
    volumes:
     - ./data/mysql:/var/lib/mysql
     - ./data/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    image: mysql:5.7.14
    environment:
     - MYSQL_ROOT_PASSWORD=phassword
