version: '2'
services:
  phabricator:
    restart: always
    ports:
     - "8080:80"
    volumes:
     - /path/to/data:/var/repos
    depends_on:
     - mysql
    links:
     - mysql
    image: phabricator
  mysql:
    restart: always
    volumes:
     - /path/to/data:/var/lib/mysql
     - /path/to/data/conf.d:/etc/mysql/conf.d
    image: mysql:5.7.14
    environment:
     - MYSQL_ROOT_PASSWORD=root_password
